### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by alexvuta** [globocom/kong-plugin-proxy-cache#7]
Hello, I try to install this plugin in a docker container (using dockerfile) but it`s not working.
Redis configuration is not recognized:
```2021/02/26 12:34:50 [error] 97#0: init_by_lua error: ...itnami/kong/openresty/luajit/share/lua/5.1/kong/init.lua:499: error parsing declarative config file /opt/kong.yml:
in 'services':
  - in entry 2 of 'services':
    in 'plugins':
      - in entry 1 of 'plugins':
        in 'config':
          in 'redis': unknown field
stack traceback:
        [C]: in function 'error'
        ...itnami/kong/openresty/luajit/share/lua/5.1/kong/init.lua:499: in function 'init'
        init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: ...itnami/kong/openresty/luajit/share/lua/5.1/kong/init.lua:499: error parsing declarative config file /opt/kong.yml:
in 'services':
  - in entry 2 of 'services':
    in 'plugins':
      - in entry 1 of 'plugins':
        in 'config':
          in 'redis': unknown field
stack traceback:
        [C]: in function 'error'
        ...itnami/kong/openresty/luajit/share/lua/5.1/kong/init.lua:499: in function 'init'
        init_by_lua:3: in main chunk
Error: ...i/kong/openresty/luajit/share/lua/5.1/kong/cmd/start.lua:64: failed to start nginx (exit code: 1)
```

Configuration used:
```
  plugins:
  - name: proxy-cache
    config:
      cache_ttl: ${KONG_DICOM_METADATA_CACHE_TTL}
      storage_ttl: ${KONG_DICOM_METADATA_CACHE_TTL}
      response_code:
      - 200
      - 301
      content_type: 
      - application/json 
      redis:
        host: redis
        port: 6379
        timeout: 2000
```
In docker:
```
RUN luarocks install kong-plugin-proxy-cache
```
Plugins enabled:
```
KONG_PLUGINS: "proxy-cache,bundled,kong-response-string-replace"
```

I am using latest bitnami image bitnami/kong in DB-less mode. Any ideas ?

Thanks!
